name: Main Win

on:
  push:
    branches: ['**']  # All branches
    tags: ['v*']      # Version tags

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: echo ${{ github.sha }} > WinRelease.txt
      - name: Test
        run: cat WinRelease.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: (github.ref_type == 'tag') && startsWith(github.ref_name, 'v')
        with:
          name: 'TEST Release ${{ github.ref_name }}'
          body_path: changes.txt
          files: |
            WinRelease.txt
            LICENSE
            path/to/artifacts/release-artifacts

