name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: 'TEST Release ${GITHUB_REF_NAME}'
          body_path: changes.txt
          files: |
            Release.txt
            LICENSE
            path/to/artifacts/release-artifacts

